-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 19:41:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CUSTOMER` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(10) NULL,
  `cust_fname` VARCHAR(45) NULL,
  `cust_lname` VARCHAR(45) NULL,
  `cust_email` VARCHAR(45) NULL,
  `cust_addr_line1` VARCHAR(45) NULL,
  `cust_addr_line2` VARCHAR(45) NULL,
  `cust_addr_city` VARCHAR(45) NULL,
  `cust_addr_state` VARCHAR(45) NULL,
  `cust_addr_zip` INT NULL,
  `cust_addr_phone` VARCHAR(12) NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORY` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM` (
  `i_id` INT NOT NULL AUTO_INCREMENT,
  `i_name` VARCHAR(45) NULL,
  `i_description` VARCHAR(120) NULL,
  `i_price` DECIMAL(6,2) NULL,
  `i_category_id` INT NULL,
  `i_image` BLOB NULL,
  `i_purchase_date` DATETIME NULL,
  `i_cust_id` INT NULL,
  `i_serialnum` VARCHAR(45) NULL,
  PRIMARY KEY (`i_id`),
  INDEX `i_category_idx` (`i_category_id` ASC),
  INDEX `i_cust_id_idx` (`i_cust_id` ASC),
  CONSTRAINT `i_category_id`
    FOREIGN KEY (`i_category_id`)
    REFERENCES `mydb`.`CATEGORY` (`cat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `i_cust_id`
    FOREIGN KEY (`i_cust_id`)
    REFERENCES `mydb`.`CUSTOMER` (`cust_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ORDER` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `o_date` DATETIME NULL,
  `o_status` VARCHAR(45) NULL,
  `o_item_id` INT NULL,
  `o_cust_id` INT NULL,
  `o_seller_Id` INT NULL,
  `o_transaction_id` INT NULL,
  `o_transaction_auth_code` INT NULL,
  PRIMARY KEY (`o_id`),
  INDEX `o_cust_id_idx` (`o_cust_id` ASC),
  INDEX `o_item_id_idx` (`o_item_id` ASC),
  CONSTRAINT `o_cust_id`
    FOREIGN KEY (`o_cust_id`)
    REFERENCES `mydb`.`CUSTOMER` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_item_id`
    FOREIGN KEY (`o_item_id`)
    REFERENCES `mydb`.`ITEM` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER_ROLE` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_value` VARCHAR(45) NULL,
  `ur_cust_id` INT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `ur_cust_id_idx` (`ur_cust_id` ASC),
  CONSTRAINT `ur_cust_id`
    FOREIGN KEY (`ur_cust_id`)
    REFERENCES `mydb`.`CUSTOMER` (`cust_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOGIN` (
  `l_id` INT NOT NULL AUTO_INCREMENT,
  `l_cust_id` INT NULL,
  `l_username` VARCHAR(45) NULL,
  `l_password` VARCHAR(45) NULL,
  `l_session_status` VARCHAR(45) NULL,
  PRIMARY KEY (`l_id`),
  INDEX `l_cust_id_idx` (`l_cust_id` ASC),
  CONSTRAINT `l_cust_id`
    FOREIGN KEY (`l_cust_id`)
    REFERENCES `mydb`.`CUSTOMER` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AFFIDAVIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AFFIDAVIT` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_item_id` INT NULL,
  `a_order_id` INT NULL,
  `a_cust_id` INT NULL,
  `a_file` BLOB NULL,
  PRIMARY KEY (`a_id`),
  INDEX `a_order_id_idx` (`a_order_id` ASC),
  INDEX `a_cust_id_idx` (`a_cust_id` ASC),
  CONSTRAINT `a_item_id`
    FOREIGN KEY (`a_item_id`)
    REFERENCES `mydb`.`ITEM` (`i_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_order_id`
    FOREIGN KEY (`a_order_id`)
    REFERENCES `mydb`.`ORDER` (`o_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_cust_id`
    FOREIGN KEY (`a_cust_id`)
    REFERENCES `mydb`.`CUSTOMER` (`cust_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
