-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 19:13:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NFTools
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NFTools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NFTools` DEFAULT CHARACTER SET utf8 ;
USE `NFTools` ;

-- -----------------------------------------------------
-- Table `NFTools`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(45) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`item` (
  `i_id` INT NOT NULL AUTO_INCREMENT,
  `i_name` VARCHAR(45) NULL,
  `i_description` VARCHAR(300) NULL,
  `i_price` DOUBLE(6,2) NULL,
  `i_image` BLOB NULL,
  `i_category_Id` INT NULL,
  `i_serialnum` INT NULL,
  PRIMARY KEY (`i_id`),
  UNIQUE INDEX `i_serialnum_UNIQUE` (`i_serialnum` ASC) VISIBLE,
  UNIQUE INDEX `i_id_UNIQUE` (`i_id` ASC) VISIBLE,
  INDEX `i_category_id_idx` (`i_category_Id` ASC) VISIBLE,
  CONSTRAINT `i_category_id`
    FOREIGN KEY (`i_category_Id`)
    REFERENCES `NFTools`.`category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `admin` TINYINT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `addr_line_1` VARCHAR(200) NULL,
  `addr_line_2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip` INT(5) NULL,
  `phone` INT(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`orders` (
  `o_id` INT NOT NULL AUTO_INCREMENT,
  `o_date` DATETIME NULL,
  `o_status` VARCHAR(45) NULL DEFAULT 'open',
  `o_item_id` INT NULL,
  `o_buyer_id` INT NULL,
  `o_seller_id` INT NULL,
  `o_transaction_id` VARCHAR(60) NULL,
  `o_transactio_auth_code` VARCHAR(60) NULL,
  PRIMARY KEY (`o_id`),
  UNIQUE INDEX `o_id_UNIQUE` (`o_id` ASC) VISIBLE,
  INDEX `o_buyer_id_idx` (`o_buyer_id` ASC) VISIBLE,
  INDEX `o_seller_id_idx` (`o_seller_id` ASC) VISIBLE,
  INDEX `o_item_id_idx` (`o_item_id` ASC) VISIBLE,
  CONSTRAINT `o_buyer_id`
    FOREIGN KEY (`o_buyer_id`)
    REFERENCES `NFTools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_seller_id`
    FOREIGN KEY (`o_seller_id`)
    REFERENCES `NFTools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `o_item_id`
    FOREIGN KEY (`o_item_id`)
    REFERENCES `NFTools`.`item` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`affidavit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`affidavit` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_item_id` INT NULL,
  `a_order_id` INT NULL,
  `a_file` BLOB NULL,
  PRIMARY KEY (`a_id`),
  INDEX `a_item_id_idx` (`a_item_id` ASC) VISIBLE,
  INDEX `a_order_id_idx` (`a_order_id` ASC) VISIBLE,
  CONSTRAINT `a_item_id`
    FOREIGN KEY (`a_item_id`)
    REFERENCES `NFTools`.`item` (`i_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `a_order_id`
    FOREIGN KEY (`a_order_id`)
    REFERENCES `NFTools`.`orders` (`o_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `cart_item_id` INT NULL,
  `cart_user_id` INT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `cart_item_id_idx` (`cart_item_id` ASC) VISIBLE,
  INDEX `cart_user_id_idx` (`cart_user_id` ASC) VISIBLE,
  CONSTRAINT `cart_item_id`
    FOREIGN KEY (`cart_item_id`)
    REFERENCES `NFTools`.`item` (`i_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cart_user_id`
    FOREIGN KEY (`cart_user_id`)
    REFERENCES `NFTools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NFTools`.`login_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NFTools`.`login_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(64) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `NFTools`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
