name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_PT }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_PT }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker-repo/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME_PT }}/nft-ools.com:v2.0.0
